Homework jsnew
airan1/TekwillSite pull request #10
Opened 2023-09-29 15:44 UTC by airan1

2023-10-02 09:46 UTC, IvanCeban requested changes

2023-10-02 09:46 UTC, IvanCeban commented on script.js
> +      if (char === 'a' || char === 'e' || char === 'i' || char === 'o' || char === 'u') {
good solution. It works. But for a limited amount of elements. Ok you have 5 vowels here and you can compare the char with each of them. But what if there are hundreds of elements to compare with? 
So I suggest you to put all the vowels into an array and check if char is in array or not. Same as we did on our practice lesson last week

2023-10-09 20:56 UTC, airan1 commented
<img width="569" alt="щас" src="https://github.com/airan1/TekwillSite/assets/92546194/ab737591-b29d-4596-9ec1-ffd6fe48ffc0">

2023-10-14 11:53 UTC, airan1 commented
<img width="513" alt="иттт" src="https://github.com/airan1/TekwillSite/assets/92546194/f0a18182-50c9-4d05-aadf-425de7948d04">

2023-10-14 12:55 UTC, merged